### ISSUE TITLE
RequestError: Timeout awaiting 'request

### ISSUE THREAD

**Issue by rio9791** [ankurk91/google-chat-electron#133]
```
RequestError: Timeout awaiting 'request' for 3000ms
    at ClientRequest.<anonymous> (/snap/google-chat-electron/37/usr/lib/google-chat-electron/resources/app.asar/node_modules/got/dist/source/core/index.js:962:65)
    at Object.onceWrapper (node:events:646:26)
    at ClientRequest.emit (node:events:538:35)
    at origin.emit (/snap/google-chat-electron/37/usr/lib/google-chat-electron/resources/app.asar/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:526:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
    at Timeout.timeoutHandler [as _onTimeout] (/snap/google-chat-electron/37/usr/lib/google-chat-electron/resources/app.asar/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
    at listOnTimeout (node:internal/timers:561:11)
    at process.processTimers (node:internal/timers:502:7)
```

---

google-chat-electron 2.16.1
Electron 19.0.1
linux 5.15.0-53-generic
Locale: en-US

**Comment by ankurk91** [comment]
It is your network issue
