### ISSUE TITLE
Error: EACCES: permission denied, open '/home/<user>/snap/google-chat-electron/2/.config/google-chat-electron/config.json'

### ISSUE THREAD

**Issue by ankurk91** [ankurk91/google-chat-electron#2]
### Platform

google-chat-electron 1.0.20
Electron 11.2.0
linux 5.8.0-38-generic
Locale: en-GB
Installed via: **snap**

### Full error
```
Unhandled Error
Error: EACCES: permission denied, open '/home/<user>/snap/google-chat-electron/2/.config/google-chat-electron/config.json'
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at ElectronStore._write (/snap/google-chat-electron/2/usr/lib/google-chat-electron/resources/app.asar/node_modules/conf/dist/source/index.js:364:16)
    at ElectronStore.set store [as store] (/snap/google-chat-electron/2/usr/lib/google-chat-electron/resources/app.asar/node_modules/conf/dist/source/index.js:282:14)
    at ElectronStore.set (/snap/google-chat-electron/2/usr/lib/google-chat-electron/resources/app.asar/node_modules/conf/dist/source/index.js:182:20)
    at BrowserWindow.saveWindowPosition (/snap/google-chat-electron/2/usr/lib/google-chat-electron/resources/app.asar/lib/main/features/windowState.js:19:30)
    at Timeout.exec [as _onTimeout] (/snap/google-chat-electron/2/usr/lib/google-chat-electron/resources/app.asar/node_modules/throttle-debounce/cjs/index.js:74:16)
```
### Ref
* https://forum.snapcraft.io/t/wip-refresh-app-awareness/10736
* https://forum.snapcraft.io/t/app-unable-to-write-to-snap-app-version-after-background-refresh/20278
* https://github.com/electron/electron/issues/23854

### Possible Workaround
```
sudo snap set core experimental.refresh-app-awareness=true
```

**Comment by ankurk91** [comment]
Released v1.2.2 with a fix.
The workaround was to instruct electron to write into `SNAP_USER_COMMON` area, which is not affected by background updates.

If someone has been using the older version of this app, they need to login to app again.
